// <auto-generated />
namespace RentVehicleFinal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addSelectedItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addSelectedItems));
        
        string IMigrationMetadata.Id
        {
            get { return "202001271435280_addSelectedItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
